HAM_CLASSNAMES= ( "actinic keratosis", "basal cell carcinoma", "benign keratosis", "dermatofibroma","melanoma","nevus", "vascular")
BCN_CLASSNAMES = ('melanoma', 'squamous cell carcinoma', 'nevus', 'basal cell carcinoma', 'seborrheic keratosis', 'actinic keratosis', 'solar lentigo', 'dermatofibroma', 'vascular lesion')
PAD_CLASSNAMES= ( "nevus",  "basal cell carcinoma","actinic keratosis", "seborrheic keratosis","squamous cell carcinoma","melanoma")
DDI_CLASSNAMES= ( 'basal-cell-carcinoma', 'epidermal-cyst', 'melanocytic-nevi', 'mycosis-fungoides', 'seborrheic-keratosis', 'verruca-vulgaris', 'others')
DERMNET_CLASSNAMES = ('light diseases and disorders of pigmentation', 'acne and rosacea photos', 'warts molluscum and other viral infections', 'seborrheic keratoses and other benign tumors', 'cellulitis impetigo and other bacterial infections', 'poison ivy photos and other contact dermatitis', 'vasculitis photos', 'urticaria hives', 'melanoma skin cancer nevi and moles', 'eczema photos', 'herpes hpv and other stds photos', 'scabies lyme disease and other infestations and bites', 'tinea ringworm candidiasis and other fungal infections', 'actinic keratosis basal cell carcinoma and other malignant lesions', 'atopic dermatitis photos', 'lupus and other connective tissue diseases', 'psoriasis pictures lichen planus and related diseases', 'nail fungus and other nail disease', 'exanthems and drug eruptions', 'hair loss photos alopecia and other hair diseases', 'systemic disease', 'vascular tumors', 'bullous disease photos')

F17K_DISEASE_82_CLASSES = ('acanthosis nigricans',
                           'acne',
                           'acne vulgaris',
                           'acquired autoimmune bullous diseaseherpes gestationis',
                           'actinic keratosis',
                           'allergic contact dermatitis',
                           'basal cell carcinoma',
                           'basal cell carcinoma morpheiform',
                           'becker nevus',
                           'calcinosis cutis',
                           'dariers disease',
                           'dermatofibroma',
                           'disseminated actinic porokeratosis',
                           'drug eruption',
                           'eczema',
                           'epidermal nevus',
                           'erythema annulare centrifigum',
                           'erythema multiforme',
                           'erythema nodosum',
                           'factitial dermatitis',
                           'fixed eruptions',
                           'folliculitis',
                           'granuloma annulare',
                           'granuloma pyogenic',
                           'hailey hailey disease',
                           'halo nevus',
                           'hidradenitis',
                           'juvenile xanthogranuloma',
                           'kaposi sarcoma',
                           'keloid',
                           'keratosis pilaris',
                           'lentigo maligna',
                           'lichen amyloidosis',
                           'lichen planus',
                           'lichen simplex',
                           'livedo reticularis',
                           'lupus erythematosus',
                           'lyme disease',
                           'lymphangioma',
                           'malignant melanoma',
                           'melanoma',
                           'milia',
                           'mucinosis',
                           'mycosis fungoides',
                           'naevus comedonicus',
                           'necrobiosis lipoidica',
                           'nematode infection',
                           'neurodermatitis',
                           'neurofibromatosis',
                           'neurotic excoriations',
                           'neutrophilic dermatoses',
                           'nevocytic nevus',
                           'papilomatosis confluentes and reticulate',
                           'pediculosis lids',
                           'photodermatoses',
                           'pilar cyst',
                           'pityriasis lichenoides chronica',
                           'pityriasis rosea',
                           'pityriasis rubra pilaris',
                           'porokeratosis actinic',
                           'porokeratosis of mibelli',
                           'prurigo nodularis',
                           'psoriasis',
                           'pyogenic granuloma',
                           'sarcoidosis',
                           'scabies',
                           'scleroderma',
                           'scleromyxedema',
                           'seborrheic keratosis',
                           'solid cystic basal cell carcinoma',
                           'squamous cell carcinoma',
                           'stasis edema',
                           'striae',
                           'superficial spreading melanoma ssm',
                           'syringoma',
                           'telangiectases',
                           'tick bite',
                           'tuberous sclerosis',
                           'tungiasis',
                           'urticaria',
                           'urticaria pigmentosa',
                           'vitiligo') # 82 classes

F17K_DISEASE_113_CLASSES = ['dermatofibroma',
                            'psoriasis',
                            'kaposi sarcoma',
                            'neutrophilic dermatoses',
                            'granuloma annulare',
                            'naevus comedonicus',
                            'milia',
                            'telangiectases',
                            'lichen planus',
                            'perioral dermatitis',
                            'paronychia',
                            'hidradenitis',
                            'neurodermatitis',
                            'necrobiosis lipoidica',
                            'superficial spreading melanoma ssm',
                            'actinic keratosis',
                            'basal cell carcinoma',
                            'acne',
                            'acne vulgaris',
                            'allergic contact dermatitis',
                            'acquired autoimmune bullous diseaseherpes gestationis',
                            'rhinophyma',
                            'porokeratosis actinic',
                            'lupus subacute',
                            'livedo reticularis',
                            'folliculitis',
                            'disseminated actinic porokeratosis',
                            'pityriasis rubra pilaris',
                            'porphyria',
                            'rosacea',
                            'melanoma',
                            'sarcoidosis',
                            'squamous cell carcinoma',
                            'prurigo nodularis',
                            'tuberous sclerosis',
                            'lentigo maligna',
                            'erythema annulare centrifigum',
                            'urticaria',
                            'pustular psoriasis',
                            'congenital nevus',
                            'dariers disease',
                            'dyshidrotic eczema',
                            'eczema',
                            'mycosis fungoides',
                            'sun damaged skin',
                            'urticaria pigmentosa',
                            'malignant melanoma',
                            'fixed eruptions',
                            'pyogenic granuloma',
                            'stevens johnson syndrome',
                            'scabies',
                            'neurofibromatosis',
                            'erythema multiforme',
                            'aplasia cutis',
                            'behcets disease',
                            'nevocytic nevus',
                            'langerhans cell histiocytosis',
                            'vitiligo',
                            'dermatomyositis',
                            'pityriasis rosea',
                            'fordyce spots',
                            'scleromyxedema',
                            'pityriasis lichenoides chronica',
                            'tick bite',
                            'scleroderma',
                            'nevus sebaceous of jadassohn',
                            'seborrheic keratosis',
                            'stasis edema',
                            'lyme disease',
                            'porokeratosis of mibelli',
                            'xanthomas',
                            'pediculosis lids',
                            'becker nevus',
                            'striae',
                            'juvenile xanthogranuloma',
                            'lupus erythematosus',
                            'acrodermatitis enteropathica',
                            'nematode infection',
                            'basal cell carcinoma morpheiform',
                            'photodermatoses',
                            'incontinentia pigmenti',
                            'drug induced pigmentary changes',
                            'granuloma pyogenic',
                            'port wine stain',
                            'keratosis pilaris',
                            'mucinosis',
                            'papilomatosis confluentes and reticulate',
                            'syringoma',
                            'acanthosis nigricans',
                            'drug eruption',
                            'xeroderma pigmentosum',
                            'halo nevus',
                            'lichen amyloidosis',
                            'ehlers danlos syndrome',
                            'solid cystic basal cell carcinoma',
                            'epidermal nevus',
                            'ichthyosis vulgaris',
                            'keloid',
                            'mucous cyst',
                            'calcinosis cutis',
                            'lymphangioma',
                            'seborrheic dermatitis',
                            'pilomatricoma',
                            'pilar cyst',
                            'erythema nodosum',
                            'neurotic excoriations',
                            'hailey hailey disease',
                            'erythema elevatum diutinum',
                            'factitial dermatitis',
                            'tungiasis',
                            'epidermolysis bullosa',
                            'myiasis',
                            'cheilitis',
                            'lichen simplex']

F17K_DISEASE_9_CLASSES = ('inflammatory',
                          'malignant epidermal',
                          'benign dermal',
                          'genodermatoses',
                          'benign epidermal',
                          'benign melanocyte',
                          'malignant dermal',
                          'malignant melanoma',
                          'malignant cutaneous lymphoma')

SKINCON_32_CLASSES = ('vesicle',
                      'papule',
                      'macule',
                      'plaque',
                      'pustule',
                      'bulla',
                      'patch',
                      'nodule',
                      'ulcer',
                      'crust',
                      'erosion',
                      'excoriation',
                      'atrophy',
                      'exudate',
                      'fissure',
                      'induration',
                      'xerosis',
                      'telangiectasia',
                      'scale',
                      'scar',
                      'friable',
                      'pedunculated',
                      'exophytic/fungating',
                      'warty/papillomatous',
                      'dome-shaped',
                      'brown(hyperpigmentation)',
                      'white(hypopigmentation)',
                      'purple',
                      'yellow',
                      'black',
                      'erythema',
                      'umbilicated')

HAM_2_CLASSNAMES = ("benign", "melanoma")

SCIN_20_CLASSNAMES = ('urticaria', 'basal cell carcinoma', 'eczema', 'tinea versicolor', 'stasis dermatitis', 'psoriasis', 'tinea', 'folliculitis', 'cyst', 'verruca vulgaris', 'acne', 'seborrheic dermatitis', 'scc/sccis', 'hidradenitis', 'scar condition', 'actinic keratosis', 'melanocytic nevus', 'melanoma', 'sk/isk', 'vitiligo')
SCIN_211_CLASSNAMES = ('inflicted skin lesions', 'prurigo nodularis', 'impetigo', 'lichen planus/lichenoid eruption', 'drug rash', 'urticaria', 'basal cell carcinoma', 'eczema', 'purpura', 'skin infection', 'tinea versicolor', 'stasis dermatitis', 'hyperpigmentation', 'psoriasis', 'infected eczema', 'pityriasis rosea', 'tinea', 'onychodystrophy', 'folliculitis', 'chronic dermatitis, nos', 'acute and chronic dermatitis', 'sweet syndrome', 'insect bite', 'allergic contact dermatitis', 'herpes simplex', 'fox-fordyce disease', 'pigmented purpuric eruption', 'cyst', 'granuloma annulare', 'herpes zoster', 'verruca vulgaris', 'confluent and reticulate papillomatosis', 'photodermatitis', 'molluscum contagiosum', 'contact purpura', 'xerosis', 'acne', 'abscess', 'rosacea', 'miliaria', 'abrasion, scrape, or scab', 'wound/abrasion', 'irritant contact dermatitis', 'o/e - ecchymoses present', 'erosion of skin', 'lichen nitidus', 'scabies', 'keratosis pilaris', 'onychomycosis', 'animal bite - wound', 'cd - contact dermatitis', 'acute dermatitis, nos', 'post-inflammatory hypopigmentation', 'ecthyma', 'hemosiderin pigmentation of skin due to venous insufficiency', 'dermatofibroma', 'seborrheic dermatitis', 'perforating dermatosis', 'lichen simplex chronicus', 'hypersensitivity', 'post-inflammatory hyperpigmentation', 'viral exanthem', 'blister', 'erythema multiforme', 'scc/sccis', 'lichen sclerosus', 'cutaneous metastasis', 'hidradenitis', 'pityriasis alba', 'cutaneous sarcoidosis', 'o/e - petechiae present', 'perioral dermatitis', 'geographic tongue', 'remove from labeling tool', 'skin and soft tissue atypical mycobacterial infection', 'livedo reticularis', 'cutaneous larva migrans', 'lichenified eczematous dermatitis', 'traumatic petechiae', 'cutaneous lupus', 'condyloma acuminatum', "grover's disease", 'foot ulcer', 'superficial wound of body region', 'scar condition', 'deep fungal infection', 'allergic contact dermatitis caused by allergenic hapten derived from plant', 'burn of skin', 'keratosis', 'intertrigo', 'lichen striatus', 'candida intertrigo', 'cellulitis', 'hematoma of skin', 'acute vesicular dermatitis', 'actinic keratosis', 'leukocytoclastic vasculitis', 'erythema ab igne', 'skin ulcer', 'koebner phenomenon', 'acute-on-chronic dyshidrotic eczema of hands', 'photocontact dermatitis [berloque dermatitis]', 'milia', 'pityriasis lichenoides', 'porokeratosis', 'pemphigus vulgaris', 'idiopathic guttate hypomelanosis', 'lymphangioma', 'cutaneous t cell lymphoma', 'venous stasis ulcer', 'acanthosis nigricans', 'erythema migrans', "kaposi's sarcoma of skin", 'varicose vein', 'erythema dyschromicum perstans', 'morbilliform eruption', 'adnexal neoplasm', 'cheilitis', 'erythema nodosum', 'keratolysis exfoliativa', 'localized skin infection', 'eruptive xanthoma', 'lichen spinulosus', 'melanocytic nevus', 'o/e - petechiae on skin', 'acne keloidalis', 'morphea/scleroderma', 'dermatitis herpetiformis', 'erythema gyratum repens', 'clavus', 'chilblain', 'arsenical keratosis', 'melanoma', 'hemangioma', 'annular erythema', 'amyloidosis of skin', 'bullous pemphigoid', 'foreign body reaction of the skin', 'relapsing polychondritis', 'melasma', 'lichenified eczema', 'sk/isk', 'burn of forearm', 'knuckle pads', 'tmep - telangiectasia macularis eruptiva perstans', 'akv - acrokeratosis verruciformis', 'hand foot and mouth disease', 'o/e - pustules', 'traumatic blister', 'vitiligo', 'inflammatory dermatosis', 'fungal dermatosis', 'pityriasis rubra pilaris', 'acute constitutional eczema', 'hk - hyperkeratosis', 'varicose veins of lower extremity', 'sunburn', 'pathergy', 'paronychia', 'fungal dermatitis', 'inverse psoriasis', 'prurigo', 'contact dermatitis, nos', 'b-cell cutaneous lymphoma', 'vasculitis of the skin', 'o/e - vesicles present', 'necrobiosis lipoidica', 'acne urticata', 'candida', 'elephantiasis nostras', 'berloque dermatitis', 'hemosiderin pigmentation of lower limb due to varicose veins of lower limb', 'parapsoriasis', 'on examination - follicular pustules', 'leukonychia', 'poikiloderma', 'ichthyosis', 'agminate folliculitis', 'phytophotodermatitis', 'eruptive odontogenic cyst', 'rheumatoid nodule', 'keratoderma', 'ecthyma gangrenosum', 'pyoderma', 'majocchi granuloma', 'acute dermatitis', 'epidermal nevus', 'histiocytosis of skin', 'pincer nail deformity', 'infection of skin', 'skin lesion in drug addict', 'unilateral laterothoracic exanthem', 'diffuse xanthoma', 'localised cutaneous vasculitis', 'pyogenic granuloma', 'syphilis', 'pressure ulcer', 'jessner lymphocytic infiltrate', 'lichenoid myxedema', 'poisoning by nematocyst', 'local infection of wound', 'hyperlinear palm', 'contact dermatitis caused by rhus diversiloba', 'melanin pigmentation due to exogenous substance', 'traction alopecia', 'nail dystrophy', 'actinic granuloma', 'traumatic ulcer', 'abrasion and/or friction burn of thigh without infection', 'petechiae', 'chicken pox exanthem')
SD_128_CLASSNAMES = ('acne keloidalis nuchae', 'acne vulgaris', 'actinic solar damage(actinic keratosis)', 'actinic solar damage(cutis rhomboidalis nuchae)', 'actinic solar damage(pigmentation)', 'actinic solar damage(solar elastosis)', 'actinic solar damage(solar purpura)', 'actinic solar damage(telangiectasia)', 'allergic contact dermatitis', 'alopecia areata', 'androgenetic alopecia', 'angioma', 'angular cheilitis', 'apocrine hydrocystoma', 'basal cell carcinoma', "beau's lines", 'benign keratosis', 'blue nevus', "bowen's disease", 'callus', 'candidiasis', 'cellulitis', 'clubbing of fingers', 'compound nevus', 'congenital nevus', "crowe's sign", 'cutaneous horn', 'darier-white disease', 'dermatofibroma', 'dermatosis papulosa nigra', 'desquamation', 'digital fibroma', 'dilated pore of winer', 'disseminated actinic porokeratosis', 'drug eruption', 'dry skin eczema', 'dyshidrosiform eczema', 'dysplastic nevus', 'eczema', 'epidermal nevus', 'epidermoid cyst', 'erythema craquele', 'erythema multiforme', 'exfoliative erythroderma', 'factitial dermatitis', 'favre racouchot', 'fibroma molle', 'fixed drug eruption', 'follicular mucinosis', 'granulation tissue', 'granuloma annulare', 'guttate psoriasis', 'halo nevus', 'herpes simplex virus', 'herpes zoster', 'hidradenitis suppurativa', 'hyperkeratosis palmaris et plantaris', 'hypertrichosis', 'ichthyosis', 'infantile atopic dermatitis', 'inverse psoriasis', 'junction nevus', 'keloid', 'keratoacanthoma', 'keratolysis exfoliativa of wende', 'keratosis pilaris', 'kerion', 'koilonychia', 'lentigo maligna melanoma', 'leukocytoclastic vasculitis', 'leukonychia', 'lichen planus', 'lichen sclerosis et atrophicus', 'lichen simplex chronicus', 'lipoma', 'livedo reticularis', 'lymphocytic infiltrate of jessner', 'malignant melanoma', 'median nail dystrophy', 'metastatic carcinoma', 'milia', 'myxoid cyst', 'nail dystrophy', 'nail psoriasis', 'neurodermatitis', 'neurofibroma', 'nevus incipiens', 'nevus sebaceous of jadassohn', 'nevus spilus', 'nummular eczema', 'onycholysis', 'onychomycosis', 'onychoschizia', 'paronychia', 'perioral dermatitis', 'pitted keratolysis', 'pityriasis rosea', 'pityrosporum folliculitis', 'pseudofolliculitis barbae', 'pseudorhinophyma', 'psoriasis', 'pustular psoriasis', 'pyogenic granuloma', 'radiodermatitis', 'rhinophyma', 'rosacea', 'scalp psoriasis', 'scar', 'sebaceous gland hyperplasia', 'seborrheic dermatitis', 'seborrheic keratosis', 'skin tag', 'stasis dermatitis', 'stasis edema', 'stasis ulcer', 'steroid acne', 'steroid use abusemisuse dermatitis', 'striae', 'syringoma', 'tinea corporis', 'tinea cruris', 'tinea faciale', 'tinea manus', 'tinea pedis', 'tinea versicolor', 'ulcer', 'verruca vulgaris', 'xerosis')
SNU_134_CLASSNAMES = ('epidermal cyst', 'paronychia', 'ota nevus', 'condyloma', 'keloid', 'alopecia areata', 'cellulitis', 'pyogenic granuloma', 'fifth disease', 'dermatofibroma', 'perioral dermatitis', 'squamous cell carcinoma', 'wart', 'riehl melanosis', 'urticaria pigmentosa', 'furuncle', 'bullous disease', 'herpes simplex', 'tinea faciale', 'lupus erythematosus', 'striae distensae', 'hemangioma', 'herpes zoster', 'malignant melanoma', 'pityriasis lichenoides et varioliformis acuta', 'pompholyx', 'nevus spilus', 'juvenile xanthogranuloma', 'actinic keratosis', 'nummular eczema', 'folliculitis', 'xerotic eczema', 'subungual hematoma', 'androgenic alopecia', 'prurigo nodularis', 'hand eczema', 'basal cell carcinoma', 'melanocytic nevus', 'lymphangioma', 'seborrheic keratosis', 'hypertrophic scar', 'idiopathic guttate hypomelanosis', 'keratoderma', 'erythema ab igne', 'lichen striatus', 'ingrowing nail', 'varicella', 'cafe au lait macule', 'poikiloderma', 'morphea', 'eczema herpeticum', 'milia', 'nail dystrophy', 'lichen nitidus', 'acanthosis nigricans', 'angular cheilitis', 'confluent and reticulated papillomatosis', 'syringoma', 'mucous cyst', 'becker nevus', 'tinea versicolor', 'psoriasis', 'port wine stain', 'neurofibromatosis', 'tinea cruris', 'xanthelasma', 'molluscum contagiosum', 'erythema annulare centrifugum', 'onychomycosis', 'scabies', 'neurofibroma', 'mucosal melanotic macule', 'rosacea', 'keratoacanthoma', 'angiofibroma', 'melanonychia', 'organoid nevus', 'nevus depigmentosus', 'epidermal nevus', 'tinea corporis', 'drug eruption', 'freckle', 'vitiligo', 'poroma', 'pityriasis alba', 'viral exanthem', 'blue nevus', 'acne', 'venous lake', 'atopic dermatitis', 'seborrheic dermatitis', 'lichen planus', 'exfoliative dermatitis', 'melasma', 'abscess', 'acute generalized exanthematous pustulosis', 'urticarial vasculitis', 'vasculitis', 'prurigo pigmentosa', 'impetigo', 'pityriasis lichenoides chronica', 'bowen disease', 'granuloma annulare', 'amyloidosis', 'urticaria', 'keratosis pilaris', 'livedo reticularis', 'steatocystoma multiplex', 'pityriasis rosea', 'mucocele', 'erythema multiforme', 'sebaceous hyperplasia', 'palmoplantar pustulosis', 'porokeratosis', 'lentigo', 'erythema nodosum', 'inflammed cyst', 'staphylococcal scalded skin syndrome', 'contact dermatitis', 'verruca plana', 'congenital nevus', 'lichen simplex chronicus', 'guttate psoriasis', 'angiokeratoma', 'tinea pedis', 'insect bite', 'pigmented progressive purpuric dermatosis', 'pyoderma gangrenosum', 'skin tag', 'lichen amyloidosis', 'abnormal', 'onycholysis', 'pustular psoriasis', 'telangiectasia')
DAFFODIL_5_CLASSNAMES = ['vitiligo', 'acne', 'SJS/TEN', 'hyperpigmentation', 'nail psoriasis']

OPENAI_SKIN_TEMPLATES = (
    lambda c: f'This is a skin image of {c}',
    lambda c: f'This is a skin image of {c}.',
    lambda c: f'A skin image of {c}.',
    lambda c: f'An image of {c}, a skin condition.',
    lambda c: f'{c}, a skin disorder, is shown in this image.',
    lambda c: f'The skin lesion depicted is {c}.',
    lambda c: f'The skin cancer in this image is {c}.',
    lambda c: f'This image depicts {c}, a type of skin cancer.',
)

OPENAI_IMAGENET_TEMPLATES = (
    lambda c: f'a bad photo of a {c}.',
    lambda c: f'a photo of many {c}.',
    lambda c: f'a sculpture of a {c}.',
    lambda c: f'a photo of the hard to see {c}.',
    lambda c: f'a low resolution photo of the {c}.',
    lambda c: f'a rendering of a {c}.',
    lambda c: f'graffiti of a {c}.',
    lambda c: f'a bad photo of the {c}.',
    lambda c: f'a cropped photo of the {c}.',
    lambda c: f'a tattoo of a {c}.',
    lambda c: f'the embroidered {c}.',
    lambda c: f'a photo of a hard to see {c}.',
    lambda c: f'a bright photo of a {c}.',
    lambda c: f'a photo of a clean {c}.',
    lambda c: f'a photo of a dirty {c}.',
    lambda c: f'a dark photo of the {c}.',
    lambda c: f'a drawing of a {c}.',
    lambda c: f'a photo of my {c}.',
    lambda c: f'the plastic {c}.',
    lambda c: f'a photo of the cool {c}.',
    lambda c: f'a close-up photo of a {c}.',
    lambda c: f'a black and white photo of the {c}.',
    lambda c: f'a painting of the {c}.',
    lambda c: f'a painting of a {c}.',
    lambda c: f'a pixelated photo of the {c}.',
    lambda c: f'a sculpture of the {c}.',
    lambda c: f'a bright photo of the {c}.',
    lambda c: f'a cropped photo of a {c}.',
    lambda c: f'a plastic {c}.',
    lambda c: f'a photo of the dirty {c}.',
    lambda c: f'a jpeg corrupted photo of a {c}.',
    lambda c: f'a blurry photo of the {c}.',
    lambda c: f'a photo of the {c}.',
    lambda c: f'a good photo of the {c}.',
    lambda c: f'a rendering of the {c}.',
    lambda c: f'a {c} in a video game.',
    lambda c: f'a photo of one {c}.',
    lambda c: f'a doodle of a {c}.',
    lambda c: f'a close-up photo of the {c}.',
    lambda c: f'a photo of a {c}.',
    lambda c: f'the origami {c}.',
    lambda c: f'the {c} in a video game.',
    lambda c: f'a sketch of a {c}.',
    lambda c: f'a doodle of the {c}.',
    lambda c: f'a origami {c}.',
    lambda c: f'a low resolution photo of a {c}.',
    lambda c: f'the toy {c}.',
    lambda c: f'a rendition of the {c}.',
    lambda c: f'a photo of the clean {c}.',
    lambda c: f'a photo of a large {c}.',
    lambda c: f'a rendition of a {c}.',
    lambda c: f'a photo of a nice {c}.',
    lambda c: f'a photo of a weird {c}.',
    lambda c: f'a blurry photo of a {c}.',
    lambda c: f'a cartoon {c}.',
    lambda c: f'art of a {c}.',
    lambda c: f'a sketch of the {c}.',
    lambda c: f'a embroidered {c}.',
    lambda c: f'a pixelated photo of a {c}.',
    lambda c: f'itap of the {c}.',
    lambda c: f'a jpeg corrupted photo of the {c}.',
    lambda c: f'a good photo of a {c}.',
    lambda c: f'a plushie {c}.',
    lambda c: f'a photo of the nice {c}.',
    lambda c: f'a photo of the small {c}.',
    lambda c: f'a photo of the weird {c}.',
    lambda c: f'the cartoon {c}.',
    lambda c: f'art of the {c}.',
    lambda c: f'a drawing of the {c}.',
    lambda c: f'a photo of the large {c}.',
    lambda c: f'a black and white photo of a {c}.',
    lambda c: f'the plushie {c}.',
    lambda c: f'a dark photo of a {c}.',
    lambda c: f'itap of a {c}.',
    lambda c: f'graffiti of the {c}.',
    lambda c: f'a toy {c}.',
    lambda c: f'itap of my {c}.',
    lambda c: f'a photo of a cool {c}.',
    lambda c: f'a photo of a small {c}.',
    lambda c: f'a tattoo of the {c}.',
)

# a much smaller subset of above prompts
# from https://github.com/openai/CLIP/blob/main/notebooks/Prompt_Engineering_for_ImageNet.ipynb
SIMPLE_IMAGENET_TEMPLATES = (
    lambda c: f'itap of a {c}.',
    lambda c: f'a bad photo of the {c}.',
    lambda c: f'a origami {c}.',
    lambda c: f'a photo of the large {c}.',
    lambda c: f'a {c} in a video game.',
    lambda c: f'art of the {c}.',
    lambda c: f'a photo of the small {c}.',
)

IMAGENET_CLASSNAMES = (
    "tench", "goldfish", "great white shark", "tiger shark", "hammerhead shark", "electric ray",
    "stingray", "rooster", "hen", "ostrich", "brambling", "goldfinch", "house finch", "junco",
    "indigo bunting", "American robin", "bulbul", "jay", "magpie", "chickadee", "American dipper",
    "kite (bird of prey)", "bald eagle", "vulture", "great grey owl", "fire salamander",
    "smooth newt", "newt", "spotted salamander", "axolotl", "American bullfrog", "tree frog",
    "tailed frog", "loggerhead sea turtle", "leatherback sea turtle", "mud turtle", "terrapin",
    "box turtle", "banded gecko", "green iguana", "Carolina anole",
    "desert grassland whiptail lizard", "agama", "frilled-necked lizard", "alligator lizard",
    "Gila monster", "European green lizard", "chameleon", "Komodo dragon", "Nile crocodile",
    "American alligator", "triceratops", "worm snake", "ring-necked snake",
    "eastern hog-nosed snake", "smooth green snake", "kingsnake", "garter snake", "water snake",
    "vine snake", "night snake", "boa constrictor", "African rock python", "Indian cobra",
    "green mamba", "sea snake", "Saharan horned viper", "eastern diamondback rattlesnake",
    "sidewinder rattlesnake", "trilobite", "harvestman", "scorpion", "yellow garden spider",
    "barn spider", "European garden spider", "southern black widow", "tarantula", "wolf spider",
    "tick", "centipede", "black grouse", "ptarmigan", "ruffed grouse", "prairie grouse", "peafowl",
    "quail", "partridge", "african grey parrot", "macaw", "sulphur-crested cockatoo", "lorikeet",
    "coucal", "bee eater", "hornbill", "hummingbird", "jacamar", "toucan", "duck",
    "red-breasted merganser", "goose", "black swan", "tusker", "echidna", "platypus", "wallaby",
    "koala", "wombat", "jellyfish", "sea anemone", "brain coral", "flatworm", "nematode", "conch",
    "snail", "slug", "sea slug", "chiton", "chambered nautilus", "Dungeness crab", "rock crab",
    "fiddler crab", "red king crab", "American lobster", "spiny lobster", "crayfish", "hermit crab",
    "isopod", "white stork", "black stork", "spoonbill", "flamingo", "little blue heron",
    "great egret", "bittern bird", "crane bird", "limpkin", "common gallinule", "American coot",
    "bustard", "ruddy turnstone", "dunlin", "common redshank", "dowitcher", "oystercatcher",
    "pelican", "king penguin", "albatross", "grey whale", "killer whale", "dugong", "sea lion",
    "Chihuahua", "Japanese Chin", "Maltese", "Pekingese", "Shih Tzu", "King Charles Spaniel",
    "Papillon", "toy terrier", "Rhodesian Ridgeback", "Afghan Hound", "Basset Hound", "Beagle",
    "Bloodhound", "Bluetick Coonhound", "Black and Tan Coonhound", "Treeing Walker Coonhound",
    "English foxhound", "Redbone Coonhound", "borzoi", "Irish Wolfhound", "Italian Greyhound",
    "Whippet", "Ibizan Hound", "Norwegian Elkhound", "Otterhound", "Saluki", "Scottish Deerhound",
    "Weimaraner", "Staffordshire Bull Terrier", "American Staffordshire Terrier",
    "Bedlington Terrier", "Border Terrier", "Kerry Blue Terrier", "Irish Terrier",
    "Norfolk Terrier", "Norwich Terrier", "Yorkshire Terrier", "Wire Fox Terrier",
    "Lakeland Terrier", "Sealyham Terrier", "Airedale Terrier", "Cairn Terrier",
    "Australian Terrier", "Dandie Dinmont Terrier", "Boston Terrier", "Miniature Schnauzer",
    "Giant Schnauzer", "Standard Schnauzer", "Scottish Terrier", "Tibetan Terrier",
    "Australian Silky Terrier", "Soft-coated Wheaten Terrier", "West Highland White Terrier",
    "Lhasa Apso", "Flat-Coated Retriever", "Curly-coated Retriever", "Golden Retriever",
    "Labrador Retriever", "Chesapeake Bay Retriever", "German Shorthaired Pointer", "Vizsla",
    "English Setter", "Irish Setter", "Gordon Setter", "Brittany dog", "Clumber Spaniel",
    "English Springer Spaniel", "Welsh Springer Spaniel", "Cocker Spaniel", "Sussex Spaniel",
    "Irish Water Spaniel", "Kuvasz", "Schipperke", "Groenendael dog", "Malinois", "Briard",
    "Australian Kelpie", "Komondor", "Old English Sheepdog", "Shetland Sheepdog", "collie",
    "Border Collie", "Bouvier des Flandres dog", "Rottweiler", "German Shepherd Dog", "Dobermann",
    "Miniature Pinscher", "Greater Swiss Mountain Dog", "Bernese Mountain Dog",
    "Appenzeller Sennenhund", "Entlebucher Sennenhund", "Boxer", "Bullmastiff", "Tibetan Mastiff",
    "French Bulldog", "Great Dane", "St. Bernard", "husky", "Alaskan Malamute", "Siberian Husky",
    "Dalmatian", "Affenpinscher", "Basenji", "pug", "Leonberger", "Newfoundland dog",
    "Great Pyrenees dog", "Samoyed", "Pomeranian", "Chow Chow", "Keeshond", "brussels griffon",
    "Pembroke Welsh Corgi", "Cardigan Welsh Corgi", "Toy Poodle", "Miniature Poodle",
    "Standard Poodle", "Mexican hairless dog (xoloitzcuintli)", "grey wolf", "Alaskan tundra wolf",
    "red wolf or maned wolf", "coyote", "dingo", "dhole", "African wild dog", "hyena", "red fox",
    "kit fox", "Arctic fox", "grey fox", "tabby cat", "tiger cat", "Persian cat", "Siamese cat",
    "Egyptian Mau", "cougar", "lynx", "leopard", "snow leopard", "jaguar", "lion", "tiger",
    "cheetah", "brown bear", "American black bear", "polar bear", "sloth bear", "mongoose",
    "meerkat", "tiger beetle", "ladybug", "ground beetle", "longhorn beetle", "leaf beetle",
    "dung beetle", "rhinoceros beetle", "weevil", "fly", "bee", "ant", "grasshopper",
    "cricket insect", "stick insect", "cockroach", "praying mantis", "cicada", "leafhopper",
    "lacewing", "dragonfly", "damselfly", "red admiral butterfly", "ringlet butterfly",
    "monarch butterfly", "small white butterfly", "sulphur butterfly", "gossamer-winged butterfly",
    "starfish", "sea urchin", "sea cucumber", "cottontail rabbit", "hare", "Angora rabbit",
    "hamster", "porcupine", "fox squirrel", "marmot", "beaver", "guinea pig", "common sorrel horse",
    "zebra", "pig", "wild boar", "warthog", "hippopotamus", "ox", "water buffalo", "bison",
    "ram (adult male sheep)", "bighorn sheep", "Alpine ibex", "hartebeest", "impala (antelope)",
    "gazelle", "arabian camel", "llama", "weasel", "mink", "European polecat",
    "black-footed ferret", "otter", "skunk", "badger", "armadillo", "three-toed sloth", "orangutan",
    "gorilla", "chimpanzee", "gibbon", "siamang", "guenon", "patas monkey", "baboon", "macaque",
    "langur", "black-and-white colobus", "proboscis monkey", "marmoset", "white-headed capuchin",
    "howler monkey", "titi monkey", "Geoffroy's spider monkey", "common squirrel monkey",
    "ring-tailed lemur", "indri", "Asian elephant", "African bush elephant", "red panda",
    "giant panda", "snoek fish", "eel", "silver salmon", "rock beauty fish", "clownfish",
    "sturgeon", "gar fish", "lionfish", "pufferfish", "abacus", "abaya", "academic gown",
    "accordion", "acoustic guitar", "aircraft carrier", "airliner", "airship", "altar", "ambulance",
    "amphibious vehicle", "analog clock", "apiary", "apron", "trash can", "assault rifle",
    "backpack", "bakery", "balance beam", "balloon", "ballpoint pen", "Band-Aid", "banjo",
    "baluster / handrail", "barbell", "barber chair", "barbershop", "barn", "barometer", "barrel",
    "wheelbarrow", "baseball", "basketball", "bassinet", "bassoon", "swimming cap", "bath towel",
    "bathtub", "station wagon", "lighthouse", "beaker", "military hat (bearskin or shako)",
    "beer bottle", "beer glass", "bell tower", "baby bib", "tandem bicycle", "bikini",
    "ring binder", "binoculars", "birdhouse", "boathouse", "bobsleigh", "bolo tie", "poke bonnet",
    "bookcase", "bookstore", "bottle cap", "hunting bow", "bow tie", "brass memorial plaque", "bra",
    "breakwater", "breastplate", "broom", "bucket", "buckle", "bulletproof vest",
    "high-speed train", "butcher shop", "taxicab", "cauldron", "candle", "cannon", "canoe",
    "can opener", "cardigan", "car mirror", "carousel", "tool kit", "cardboard box / carton",
    "car wheel", "automated teller machine", "cassette", "cassette player", "castle", "catamaran",
    "CD player", "cello", "mobile phone", "chain", "chain-link fence", "chain mail", "chainsaw",
    "storage chest", "chiffonier", "bell or wind chime", "china cabinet", "Christmas stocking",
    "church", "movie theater", "cleaver", "cliff dwelling", "cloak", "clogs", "cocktail shaker",
    "coffee mug", "coffeemaker", "spiral or coil", "combination lock", "computer keyboard",
    "candy store", "container ship", "convertible", "corkscrew", "cornet", "cowboy boot",
    "cowboy hat", "cradle", "construction crane", "crash helmet", "crate", "infant bed",
    "Crock Pot", "croquet ball", "crutch", "cuirass", "dam", "desk", "desktop computer",
    "rotary dial telephone", "diaper", "digital clock", "digital watch", "dining table",
    "dishcloth", "dishwasher", "disc brake", "dock", "dog sled", "dome", "doormat", "drilling rig",
    "drum", "drumstick", "dumbbell", "Dutch oven", "electric fan", "electric guitar",
    "electric locomotive", "entertainment center", "envelope", "espresso machine", "face powder",
    "feather boa", "filing cabinet", "fireboat", "fire truck", "fire screen", "flagpole", "flute",
    "folding chair", "football helmet", "forklift", "fountain", "fountain pen", "four-poster bed",
    "freight car", "French horn", "frying pan", "fur coat", "garbage truck",
    "gas mask or respirator", "gas pump", "goblet", "go-kart", "golf ball", "golf cart", "gondola",
    "gong", "gown", "grand piano", "greenhouse", "radiator grille", "grocery store", "guillotine",
    "hair clip", "hair spray", "half-track", "hammer", "hamper", "hair dryer", "hand-held computer",
    "handkerchief", "hard disk drive", "harmonica", "harp", "combine harvester", "hatchet",
    "holster", "home theater", "honeycomb", "hook", "hoop skirt", "gymnastic horizontal bar",
    "horse-drawn vehicle", "hourglass", "iPod", "clothes iron", "carved pumpkin", "jeans", "jeep",
    "T-shirt", "jigsaw puzzle", "rickshaw", "joystick", "kimono", "knee pad", "knot", "lab coat",
    "ladle", "lampshade", "laptop computer", "lawn mower", "lens cap", "letter opener", "library",
    "lifeboat", "lighter", "limousine", "ocean liner", "lipstick", "slip-on shoe", "lotion",
    "music speaker", "loupe magnifying glass", "sawmill", "magnetic compass", "messenger bag",
    "mailbox", "tights", "one-piece bathing suit", "manhole cover", "maraca", "marimba", "mask",
    "matchstick", "maypole", "maze", "measuring cup", "medicine cabinet", "megalith", "microphone",
    "microwave oven", "military uniform", "milk can", "minibus", "miniskirt", "minivan", "missile",
    "mitten", "mixing bowl", "mobile home", "ford model t", "modem", "monastery", "monitor",
    "moped", "mortar and pestle", "graduation cap", "mosque", "mosquito net", "vespa",
    "mountain bike", "tent", "computer mouse", "mousetrap", "moving van", "muzzle", "metal nail",
    "neck brace", "necklace", "baby pacifier", "notebook computer", "obelisk", "oboe", "ocarina",
    "odometer", "oil filter", "pipe organ", "oscilloscope", "overskirt", "bullock cart",
    "oxygen mask", "product packet / packaging", "paddle", "paddle wheel", "padlock", "paintbrush",
    "pajamas", "palace", "pan flute", "paper towel", "parachute", "parallel bars", "park bench",
    "parking meter", "railroad car", "patio", "payphone", "pedestal", "pencil case",
    "pencil sharpener", "perfume", "Petri dish", "photocopier", "plectrum", "Pickelhaube",
    "picket fence", "pickup truck", "pier", "piggy bank", "pill bottle", "pillow", "ping-pong ball",
    "pinwheel", "pirate ship", "drink pitcher", "block plane", "planetarium", "plastic bag",
    "plate rack", "farm plow", "plunger", "Polaroid camera", "pole", "police van", "poncho",
    "pool table", "soda bottle", "plant pot", "potter's wheel", "power drill", "prayer rug",
    "printer", "prison", "missile", "projector", "hockey puck", "punching bag", "purse", "quill",
    "quilt", "race car", "racket", "radiator", "radio", "radio telescope", "rain barrel",
    "recreational vehicle", "fishing casting reel", "reflex camera", "refrigerator",
    "remote control", "restaurant", "revolver", "rifle", "rocking chair", "rotisserie", "eraser",
    "rugby ball", "ruler measuring stick", "sneaker", "safe", "safety pin", "salt shaker", "sandal",
    "sarong", "saxophone", "scabbard", "weighing scale", "school bus", "schooner", "scoreboard",
    "CRT monitor", "screw", "screwdriver", "seat belt", "sewing machine", "shield", "shoe store",
    "shoji screen / room divider", "shopping basket", "shopping cart", "shovel", "shower cap",
    "shower curtain", "ski", "balaclava ski mask", "sleeping bag", "slide rule", "sliding door",
    "slot machine", "snorkel", "snowmobile", "snowplow", "soap dispenser", "soccer ball", "sock",
    "solar thermal collector", "sombrero", "soup bowl", "keyboard space bar", "space heater",
    "space shuttle", "spatula", "motorboat", "spider web", "spindle", "sports car", "spotlight",
    "stage", "steam locomotive", "through arch bridge", "steel drum", "stethoscope", "scarf",
    "stone wall", "stopwatch", "stove", "strainer", "tram", "stretcher", "couch", "stupa",
    "submarine", "suit", "sundial", "sunglasses", "sunglasses", "sunscreen", "suspension bridge",
    "mop", "sweatshirt", "swim trunks / shorts", "swing", "electrical switch", "syringe",
    "table lamp", "tank", "tape player", "teapot", "teddy bear", "television", "tennis ball",
    "thatched roof", "front curtain", "thimble", "threshing machine", "throne", "tile roof",
    "toaster", "tobacco shop", "toilet seat", "torch", "totem pole", "tow truck", "toy store",
    "tractor", "semi-trailer truck", "tray", "trench coat", "tricycle", "trimaran", "tripod",
    "triumphal arch", "trolleybus", "trombone", "hot tub", "turnstile", "typewriter keyboard",
    "umbrella", "unicycle", "upright piano", "vacuum cleaner", "vase", "vaulted or arched ceiling",
    "velvet fabric", "vending machine", "vestment", "viaduct", "violin", "volleyball",
    "waffle iron", "wall clock", "wallet", "wardrobe", "military aircraft", "sink",
    "washing machine", "water bottle", "water jug", "water tower", "whiskey jug", "whistle",
    "hair wig", "window screen", "window shade", "Windsor tie", "wine bottle", "airplane wing",
    "wok", "wooden spoon", "wool", "split-rail fence", "shipwreck", "sailboat", "yurt", "website",
    "comic book", "crossword", "traffic or street sign", "traffic light", "dust jacket", "menu",
    "plate", "guacamole", "consomme", "hot pot", "trifle", "ice cream", "popsicle", "baguette",
    "bagel", "pretzel", "cheeseburger", "hot dog", "mashed potatoes", "cabbage", "broccoli",
    "cauliflower", "zucchini", "spaghetti squash", "acorn squash", "butternut squash", "cucumber",
    "artichoke", "bell pepper", "cardoon", "mushroom", "Granny Smith apple", "strawberry", "orange",
    "lemon", "fig", "pineapple", "banana", "jackfruit", "cherimoya (custard apple)", "pomegranate",
    "hay", "carbonara", "chocolate syrup", "dough", "meatloaf", "pizza", "pot pie", "burrito",
    "red wine", "espresso", "tea cup", "eggnog", "mountain", "bubble", "cliff", "coral reef",
    "geyser", "lakeshore", "promontory", "sandbar", "beach", "valley", "volcano", "baseball player",
    "bridegroom", "scuba diver", "rapeseed", "daisy", "yellow lady's slipper", "corn", "acorn",
    "rose hip", "horse chestnut seed", "coral fungus", "agaric", "gyromitra", "stinkhorn mushroom",
    "earth star fungus", "hen of the woods mushroom", "bolete", "corn cob", "toilet paper"
)

# --- Ontology aug class
SD_128_CLASSNAMES_ONTOLOGY_AUG = ['inflammatory, non-infectious, Acne keloidalis nuchae', 'inflammatory, non-infectious, Acne vulgaris', 'exogenous, Actinic solar damage(actinic keratosis), Actinic keratosis', 'exogenous, Actinic solar damage(cutis rhomboidalis nuchae)', 'exogenous, Actinic solar damage(pigmentation)', 'exogenous, Actinic solar damage(solar elastosis)', 'exogenous, Actinic solar damage(solar purpura)', 'exogenous, Actinic solar damage(telangiectasia)', 'inflammatory, non-infectious, Eczema, Allergic contact dermatitis', 'Hair diseases, Alopecia areata', 'Hair diseases, Androgenetic alopecia', 'proliferations, benign, non-melanocytic, Angioma, Hemangioma', 'inflammatory, non-infectious, Angular cheilitis', 'proliferations, benign, non-melanocytic, Apocrine hydrocystoma', 'proliferations, malignant, non-melanocytic, Basal cell carcinoma', "Nail diseases, nail disease, Beau's lines", 'proliferations, benign, non-melanocytic, Benign keratosis', 'proliferations, benign, melanocytic, Blue nevus', "proliferations, malignant, non-melanocytic, Bowen's disease", 'reaction patterns and descriptive terms, Callus', 'inflammatory, infectious, fungal, Candidiasis', 'inflammatory, infectious, bacterial, Cellulitis', 'reaction patterns and descriptive terms, Clubbing of fingers', 'proliferations, benign, melanocytic, Compound nevus', 'proliferations, benign, melanocytic, Congenital nevus', "hereditary, Crowe's sign", 'reaction patterns and descriptive terms, Cutaneous horn', 'hereditary, Darier-White disease, Dariers disease', 'proliferations, benign, non-melanocytic, Dermatofibroma', 'proliferations, benign, non-melanocytic, Dermatosis papulosa nigra', 'reaction patterns and descriptive terms, Desquamation', 'proliferations, benign, non-melanocytic, Digital fibroma', 'proliferations, benign, non-melanocytic, Dilated pore of Winer', 'inflammatory, non-infectious, Disseminated actinic porokeratosis', 'inflammatory, non-infectious, Drug eruption, Drug eruptions & reactions', 'inflammatory, non-infectious, Eczema, Dry skin eczema', 'inflammatory, non-infectious, Eczema, Dyshidrosiform eczema', 'proliferations, benign, melanocytic, Dysplastic nevus', 'inflammatory, non-infectious, Eczema', 'proliferations, benign, non-melanocytic, Epidermal nevus', 'proliferations, cysts, cyst, Epidermoid cyst', 'reaction patterns and descriptive terms, Erythema craquele', 'inflammatory, non-infectious, Erythema multiforme', 'reaction patterns and descriptive terms, Exfoliative erythroderma', 'exogenous, physical, Factitial dermatitis', 'exogenous, Favre Racouchot', 'proliferations, benign, non-melanocytic, Fibroma molle', 'inflammatory, non-infectious, Fixed drug eruption', 'reaction patterns and descriptive terms, Follicular mucinosis', 'reaction patterns and descriptive terms, Granulation tissue', 'inflammatory, non-infectious, Granuloma annulare', 'inflammatory, non-infectious, Psoriasis, Guttate psoriasis', 'proliferations, benign, melanocytic, halo nevus', 'inflammatory, infectious, viral, Herpes simplex virus', 'inflammatory, infectious, viral, Herpes zoster', 'inflammatory, non-infectious, hidradenitis suppurativa', 'reaction patterns and descriptive terms, Hyperkeratosis palmaris et plantaris', 'Hair diseases, Hypertrichosis', 'hereditary, Ichthyosis', 'inflammatory, non-infectious, Eczema, Infantile atopic dermatitis', 'inflammatory, non-infectious, Psoriasis, Inverse psoriasis', 'proliferations, benign, melanocytic, Junction nevus', 'proliferations, benign, non-melanocytic, Keloid', 'proliferations, malignant, non-melanocytic, Keratoacanthoma', 'inflammatory, non-infectious, Eczema, keratolysis exfoliativa of wende', 'hereditary, Keratosis pilaris', 'inflammatory, infectious, fungal, Kerion', 'Nail diseases, nail disease, Koilonychia', 'proliferations, malignant, melanocytic, Lentigo maligna melanoma, Lentigo maligna', 'inflammatory, non-infectious, Leukocytoclastic vasculitis', 'Nail diseases, nail disease, Leukonychia', 'inflammatory, non-infectious, Lichen planus', 'inflammatory, non-infectious, lichen sclerosis et atrophicus, Lichen sclerosus et atrophicus', 'inflammatory, non-infectious, Eczema, Lichen simplex chronicus, ', 'proliferations, benign, non-melanocytic, Lipoma', 'reaction patterns and descriptive terms, Livedo reticularis', 'inflammatory, non-infectious, Lymphocytic infiltrate of jessner', 'proliferations, malignant, melanocytic, Malignant melanoma, melanoma', 'Nail diseases, nail disease, Median nail dystrophy', 'proliferations, malignant, non-melanocytic, Metastatic carcinoma', 'proliferations, benign, non-melanocytic, Milia', 'proliferations, cysts, cyst, Myxoid cyst', 'Nail diseases, nail disease, Nail dystrophy', 'Nail diseases, nail disease, Nail psoriasis', 'inflammatory, non-infectious, Eczema, Neurodermatitis', 'proliferations, benign, non-melanocytic, Neurofibroma', 'proliferations, benign, melanocytic, nevus incipiens', 'proliferations, benign, non-melanocytic, Nevus sebaceous of Jadassohn', 'proliferations, benign, melanocytic, nevus spilus', 'inflammatory, non-infectious, Eczema, Nummular eczema', 'Nail diseases, nail disease, Onycholysis', 'Nail diseases, nail disease, Onychomycosis', 'Nail diseases, nail disease, Onychoschizia', 'Nail diseases, nail disease, Paronychia', 'inflammatory, non-infectious, perioral dermatitis', 'inflammatory, infectious, bacterial, Pitted keratolysis', 'inflammatory, non-infectious, Pityriasis rosea', 'inflammatory, infectious, fungal, Pityrosporum folliculitis', 'inflammatory, non-infectious, pseudofolliculitis barbae', 'reaction patterns and descriptive terms, Pseudorhinophyma', 'inflammatory, non-infectious, Psoriasis', 'inflammatory, non-infectious, Psoriasis, Pustular psoriasis', 'proliferations, benign, non-melanocytic, Pyogenic granuloma', 'exogenous, physical, Radiodermatitis', 'inflammatory, non-infectious, Rhinophyma', 'inflammatory, non-infectious, Rosacea', 'inflammatory, non-infectious, Psoriasis, Scalp psoriasis', 'reaction patterns and descriptive terms, Scar', 'proliferations, benign, non-melanocytic, Sebaceous gland hyperplasia, Sebaceous hyperplasia', 'inflammatory, non-infectious, Eczema, Seborrheic dermatitis', 'proliferations, benign, non-melanocytic, Seborrheic keratosis', 'proliferations, benign, non-melanocytic, Skin tag', 'inflammatory, non-infectious, Stasis dermatitis', 'reaction patterns and descriptive terms, Stasis edema', 'reaction patterns and descriptive terms, Ulcers, Erosion of skin, Stasis ulcer', 'inflammatory, non-infectious, steroid acne', 'reaction patterns and descriptive terms, Steroid use abuse, Steroid use abusemisuse dermatitis', 'reaction patterns and descriptive terms, Striae', 'proliferations, benign, non-melanocytic, Syringoma', 'inflammatory, infectious, fungal, Tinea corporis', 'inflammatory, infectious, fungal, Tinea cruris', 'inflammatory, infectious, fungal, Tinea faciale', 'inflammatory, infectious, fungal, Tinea manus', 'inflammatory, infectious, fungal, Tinea pedis', 'inflammatory, infectious, fungal, Tinea versicolor', 'reaction patterns and descriptive terms, Ulcers, Erosion of skin, Ulcer', 'proliferations, benign, non-melanocytic, Verruca vulgaris', 'reaction patterns and descriptive terms, Xerosis']
SNU_134_CLASSNAMES_ONTOLOGY_AUG = ['epidermal cyst', 'Nail diseases, nail disease, Paronychia', 'proliferations, benign, melanocytic, Ota nevus', 'inflammatory, infectious, viral, Condyloma acuminatum, Condyloma', 'proliferations, benign, non-melanocytic, Keloid', 'Hair diseases, Alopecia areata', 'inflammatory, infectious, bacterial, Cellulitis', 'proliferations, benign, non-melanocytic, Pyogenic granuloma', 'fifth disease', 'proliferations, benign, non-melanocytic, Dermatofibroma', 'inflammatory, non-infectious, perioral dermatitis', 'proliferations, malignant, non-melanocytic, Squamous cell carcinoma', 'wart', 'reaction patterns and descriptive terms, Hyperpigmentation, Riehl melanosis', 'reaction patterns and descriptive terms, Hypersensitivity, allergic reaction, Urticaria, Urticaria pigmentosa', 'inflammatory, infectious, bacterial, Folliculitis, Furuncle', 'inflammatory, non-infectious, Bullous disease', 'herpes simplex', 'inflammatory, infectious, fungal, Tinea faciale', 'inflammatory, non-infectious, Cutaneous lupus, Lupus erythematosus', 'striae distensae', 'proliferations, benign, non-melanocytic, Angioma, Hemangioma', 'inflammatory, infectious, viral, Herpes zoster', 'proliferations, malignant, melanocytic, Malignant melanoma, melanoma', 'inflammatory, non-infectious, Pityriasis lichenoides, Pityriasis lichenoides et varioliformis acuta', 'pompholyx', 'proliferations, benign, melanocytic, nevus spilus', 'proliferations, benign, non-melanocytic, Juvenile xanthogranuloma', 'exogenous, Actinic solar damage(actinic keratosis), Actinic keratosis', 'inflammatory, non-infectious, Eczema, Nummular eczema', 'inflammatory, infectious, bacterial, Folliculitis', 'reaction patterns and descriptive terms, Xerosis, Xerotic eczema', 'subungual hematoma', 'androgenic alopecia', 'inflammatory, non-infectious, Prurigo, Prurigo nodularis', 'inflammatory, non-infectious, Eczema, Hand eczema', 'proliferations, malignant, non-melanocytic, Basal cell carcinoma', 'proliferations, benign, melanocytic, Melanocytic nevus', 'proliferations, malignant, non-melanocytic, Lymphangioma', 'proliferations, benign, non-melanocytic, Seborrheic keratosis', 'reaction patterns and descriptive terms, Scar, Hypertrophic scar', 'reaction patterns and descriptive terms, Idiopathic guttate hypomelanosis', 'hereditary, Keratoderma, Hyperkeratosis palmaris et plantaris', 'erythema ab igne', 'inflammatory, non-infectious, Lichen striatus', 'ingrowing nail', 'inflammatory, infectious, viral, Varicella', 'cafe au lait macule', 'reaction patterns and descriptive terms, Poikiloderma', 'inflammatory, non-infectious, Morphea', 'eczema herpeticum', 'proliferations, benign, non-melanocytic, Milia', 'Nail diseases, nail disease, Nail dystrophy', 'lichen nitidus', 'reaction patterns and descriptive terms, Acanthosis nigricans', 'inflammatory, non-infectious, Angular cheilitis', 'inflammatory, non-infectious, Confluent and reticulated papillomatosis', 'proliferations, benign, non-melanocytic, Syringoma', 'mucous cyst', 'proliferations, benign, melanocytic, Becker nevus', 'inflammatory, infectious, fungal, Tinea versicolor', 'inflammatory, non-infectious, Psoriasis', 'proliferations, benign, non-melanocytic, Port wine stain', 'hereditary, Neurofibromatosis', 'inflammatory, infectious, fungal, Tinea cruris', 'proliferations, benign, non-melanocytic, Xanthelasma', 'inflammatory, infectious, viral, Molluscum contagiosum', 'inflammatory, non-infectious, Erythema annulare centrifugum', 'Nail diseases, nail disease, Onychomycosis', 'inflammatory, infectious, parasitic, Scabies', 'proliferations, benign, non-melanocytic, Neurofibroma', 'proliferations, malignant, melanocytic, Mucosal melanotic macule', 'inflammatory, non-infectious, Rosacea', 'proliferations, malignant, non-melanocytic, Keratoacanthoma', 'proliferations, benign, non-melanocytic, Angiofibroma', 'melanonychia', 'proliferations, benign, melanocytic, Organoid nevus', 'proliferations, benign, melanocytic, Nevus depigmentosus', 'proliferations, benign, non-melanocytic, Epidermal nevus', 'inflammatory, infectious, fungal, Tinea corporis', 'inflammatory, non-infectious, Drug eruption, Drug eruptions & reactions', 'freckle', 'reaction patterns and descriptive terms, Vitiligo', 'proliferations, benign, non-melanocytic, Poroma', 'pityriasis alba', 'inflammatory, infectious, viral, Viral exanthem', 'proliferations, benign, melanocytic, Blue nevus', 'acne', 'proliferations, benign, non-melanocytic, Venous lake', 'inflammatory, non-infectious, Atopic dermatitis', 'inflammatory, non-infectious, Eczema, Seborrheic dermatitis', 'inflammatory, non-infectious, Lichen planus', 'inflammatory, Dermatitis (acute and chronic), Exfoliative dermatitis', 'proliferations, benign, melanocytic, Melasma, Lentigo', 'inflammatory, infectious, bacterial, Pyoderma, Abscess', 'inflammatory, non-infectious, Acute generalized exanthematous pustulosis', 'inflammatory, non-infectious, Urticarial vasculitis', 'vasculitis', 'inflammatory, non-infectious, Prurigo, Prurigo pigmentosa', 'inflammatory, infectious, bacterial, Pyoderma, Impetigo', 'inflammatory, non-infectious, Pityriasis lichenoides, Pityriasis lichenoides chronica', 'bowen disease', 'inflammatory, non-infectious, Granuloma annulare', 'proliferations, benign, non-melanocytic, Amyloidosis', 'reaction patterns and descriptive terms, Hypersensitivity, allergic reaction, Urticaria', 'hereditary, Keratosis pilaris', 'reaction patterns and descriptive terms, Livedo reticularis', 'proliferations, cysts, cyst, Steatocystoma multiplex', 'inflammatory, non-infectious, Pityriasis rosea', 'proliferations, cysts, cyst, Mucocele', 'inflammatory, non-infectious, Erythema multiforme', 'proliferations, benign, non-melanocytic, Sebaceous gland hyperplasia, Sebaceous hyperplasia', 'inflammatory, non-infectious, Palmoplantar pustulosis', 'proliferations, benign, non-melanocytic, Porokeratosis', 'proliferations, benign, melanocytic, Melasma, Lentigo', 'inflammatory, non-infectious, Erythema nodosum', 'inflammed cyst', 'inflammatory, infectious, bacterial, Staphylococcal scalded skin syndrome', 'inflammatory, non-infectious, Eczema, Contact dermatitis', 'verruca plana', 'proliferations, benign, melanocytic, Congenital nevus', 'inflammatory, non-infectious, Eczema, Lichen simplex chronicus, ', 'inflammatory, non-infectious, Psoriasis, Guttate psoriasis', 'proliferations, benign, non-melanocytic, Angiokeratoma', 'inflammatory, infectious, fungal, Tinea pedis', 'inflammatory, infectious, parasitic, Insect bite', 'inflammatory, non-infectious, Pigmented purpuric eruption, Pigmented progressive purpuric dermatosis', 'inflammatory, non-infectious, Pyoderma gangrenosum', 'proliferations, benign, non-melanocytic, Skin tag', 'lichen amyloidosis', 'abnormal', 'Nail diseases, nail disease, Onycholysis', 'inflammatory, non-infectious, Psoriasis, Pustular psoriasis', 'telangiectasia']
DAFFODIL_5_CLASSNAMES_ONTOLOGY_AUG = ['reaction patterns and descriptive terms, Vitiligo', 'acne', 'SJS/TEN', 'reaction patterns and descriptive terms, Hyperpigmentation', 'Nail diseases, nail disease, Nail psoriasis']
F17K_DISEASE_113_CLASSES_ONTOLOGY_AUG = ['proliferations, benign, non-melanocytic, Dermatofibroma', 'inflammatory, non-infectious, Psoriasis', 'proliferations, malignant, non-melanocytic, Kaposi sarcoma', 'inflammatory, non-infectious, Neutrophilic dermatoses', 'inflammatory, non-infectious, Granuloma annulare', 'proliferations, benign, melanocytic, Naevus comedonicus', 'proliferations, benign, non-melanocytic, Milia', 'telangiectases', 'inflammatory, non-infectious, Lichen planus', 'inflammatory, non-infectious, perioral dermatitis', 'Nail diseases, nail disease, Paronychia', 'hidradenitis', 'inflammatory, non-infectious, Eczema, Neurodermatitis', 'inflammatory, non-infectious, Necrobiosis lipoidica', 'proliferations, malignant, melanocytic, Superficial spreading melanoma SSM', 'exogenous, Actinic solar damage(actinic keratosis), Actinic keratosis', 'proliferations, malignant, non-melanocytic, Basal cell carcinoma', 'acne', 'inflammatory, non-infectious, Acne vulgaris', 'inflammatory, non-infectious, Eczema, Allergic contact dermatitis', 'inflammatory, non-infectious, Bullous disease, acquired autoimmune bullous diseaseherpes gestationis', 'inflammatory, non-infectious, Rhinophyma', 'porokeratosis actinic', 'lupus subacute', 'reaction patterns and descriptive terms, Livedo reticularis', 'inflammatory, infectious, bacterial, Folliculitis', 'inflammatory, non-infectious, Disseminated actinic porokeratosis', 'inflammatory, non-infectious, Pityriasis rubra pilaris', 'hereditary, Porphyria', 'inflammatory, non-infectious, Rosacea', 'proliferations, malignant, melanocytic, Malignant melanoma, melanoma', 'inflammatory, non-infectious, Sarcoidosis, Cutaneous sarcoidosis', 'proliferations, malignant, non-melanocytic, Squamous cell carcinoma', 'inflammatory, non-infectious, Prurigo, Prurigo nodularis', 'hereditary, Tuberous sclerosis', 'proliferations, malignant, melanocytic, Lentigo maligna melanoma, Lentigo maligna', 'erythema annulare centrifigum', 'reaction patterns and descriptive terms, Hypersensitivity, allergic reaction, Urticaria', 'inflammatory, non-infectious, Psoriasis, Pustular psoriasis', 'proliferations, benign, melanocytic, Congenital nevus', 'hereditary, Darier-White disease, Dariers disease', 'dyshidrotic eczema', 'inflammatory, non-infectious, Eczema', 'inflammatory, infectious, bacterial, Mycosis fungoides', 'sun damaged skin', 'reaction patterns and descriptive terms, Hypersensitivity, allergic reaction, Urticaria, Urticaria pigmentosa', 'proliferations, malignant, melanocytic, Malignant melanoma, melanoma', 'fixed eruptions', 'proliferations, benign, non-melanocytic, Pyogenic granuloma', 'stevens johnson syndrome', 'inflammatory, infectious, parasitic, Scabies', 'hereditary, Neurofibromatosis', 'inflammatory, non-infectious, Erythema multiforme', 'aplasia cutis', 'inflammatory, non-infectious, Behcets disease', 'nevocytic nevus', 'proliferations, benign, non-melanocytic, Langerhans cell histiocytosis', 'reaction patterns and descriptive terms, Vitiligo', 'dermatomyositis', 'inflammatory, non-infectious, Pityriasis rosea', 'fordyce spots', 'proliferations, benign, non-melanocytic, Scleromyxedema', 'inflammatory, non-infectious, Pityriasis lichenoides, Pityriasis lichenoides chronica', 'inflammatory, infectious, parasitic, Tick bite', 'scleroderma', 'proliferations, benign, non-melanocytic, Nevus sebaceous of Jadassohn', 'proliferations, benign, non-melanocytic, Seborrheic keratosis', 'reaction patterns and descriptive terms, Stasis edema', 'inflammatory, infectious, bacterial, Lyme disease', 'proliferations, benign, non-melanocytic, Porokeratosis, Porokeratosis of Mibelli', 'xanthomas', 'pediculosis lids', 'proliferations, benign, melanocytic, Becker nevus', 'reaction patterns and descriptive terms, Striae', 'proliferations, benign, non-melanocytic, Juvenile xanthogranuloma', 'inflammatory, non-infectious, Cutaneous lupus, Lupus erythematosus', 'acrodermatitis enteropathica', 'inflammatory, infectious, parasitic, Nematode infection', 'basal cell carcinoma morpheiform', 'photodermatoses', 'incontinentia pigmenti', 'drug induced pigmentary changes', 'granuloma pyogenic', 'proliferations, benign, non-melanocytic, Port wine stain', 'hereditary, Keratosis pilaris', 'proliferations, malignant, non-melanocytic, Mucinosis', 'papilomatosis confluentes and reticulate', 'proliferations, benign, non-melanocytic, Syringoma', 'reaction patterns and descriptive terms, Acanthosis nigricans', 'inflammatory, non-infectious, Drug eruption, Drug eruptions & reactions', 'hereditary, Xeroderma pigmentosum', 'proliferations, benign, melanocytic, halo nevus', 'lichen amyloidosis', 'hereditary, Ehlers danlos syndrome', 'solid cystic basal cell carcinoma', 'proliferations, benign, non-melanocytic, Epidermal nevus', 'ichthyosis vulgaris', 'proliferations, benign, non-melanocytic, Keloid', 'mucous cyst', 'proliferations, benign, non-melanocytic, Calcinosis cutis', 'proliferations, malignant, non-melanocytic, Lymphangioma', 'inflammatory, non-infectious, Eczema, Seborrheic dermatitis', 'pilomatricoma', 'proliferations, cysts, cyst, Pilar cyst', 'inflammatory, non-infectious, Erythema nodosum', 'neurotic excoriations', 'hereditary, Hailey hailey disease', 'reaction patterns and descriptive terms, Erythema elevatum diutinum', 'exogenous, physical, Factitial dermatitis', 'inflammatory, infectious, parasitic, Tungiasis', 'hereditary, Epidermolysis bullosa', 'myiasis', 'inflammatory, non-infectious, Eczema, Cheilitis', 'lichen simplex']
PAD_CLASSNAMES_ONTOLOGY_AUG = ['nevus', 'proliferations, malignant, non-melanocytic, Basal cell carcinoma', 'exogenous, Actinic solar damage(actinic keratosis), Actinic keratosis', 'proliferations, benign, non-melanocytic, Seborrheic keratosis', 'proliferations, malignant, non-melanocytic, Squamous cell carcinoma', 'proliferations, malignant, melanocytic, Malignant melanoma, melanoma']

# ---------------------------------------------------------------------------
# Long-tail / hierarchical evaluation splits (used by src/test.py)
# ---------------------------------------------------------------------------
# 10% tail class - 26 diseases
SD_128_tails_10_CLASSNAMES = ['actinic solar damage(cutis rhomboidalis nuchae)', 'actinic solar damage(solar purpura)', 'callus', "crowe's sign", 'desquamation', 'digital fibroma', 'dilated pore of winer', 'erythema multiforme', 'granulation tissue', 'granuloma annulare', 'guttate psoriasis', 'herpes simplex virus', 'herpes zoster', 'keratolysis exfoliativa of wende', 'koilonychia', 'leukocytoclastic vasculitis', 'lipoma', 'median nail dystrophy', 'neurodermatitis', 'onychoschizia', 'paronychia', 'pitted keratolysis', 'pseudofolliculitis barbae', 'pseudorhinophyma', 'ulcer', 'verruca vulgaris']

# 30% tail class - 60 diseases
SD_128_tails_30_CLASSNAMES = ['acne keloidalis nuchae', 'actinic solar damage(cutis rhomboidalis nuchae)', 'actinic solar damage(solar purpura)', 'androgenetic alopecia', 'apocrine hydrocystoma', "beau's lines", 'callus', 'cellulitis', 'clubbing of fingers', "crowe's sign", 'darier-white disease', 'dermatosis papulosa nigra', 'desquamation', 'digital fibroma', 'dilated pore of winer', 'disseminated actinic porokeratosis', 'epidermal nevus', 'erythema craquele', 'erythema multiforme', 'exfoliative erythroderma', 'fixed drug eruption', 'follicular mucinosis', 'granulation tissue', 'granuloma annulare', 'guttate psoriasis', 'herpes simplex virus', 'herpes zoster', 'hidradenitis suppurativa', 'hyperkeratosis palmaris et plantaris', 'hypertrichosis', 'infantile atopic dermatitis', 'junction nevus', 'keratolysis exfoliativa of wende', 'kerion', 'koilonychia', 'leukocytoclastic vasculitis', 'leukonychia', 'lichen simplex chronicus', 'lipoma', 'livedo reticularis', 'median nail dystrophy', 'metastatic carcinoma', 'nail dystrophy', 'neurodermatitis', 'nevus sebaceous of jadassohn', 'nevus spilus', 'onychoschizia', 'paronychia', 'pitted keratolysis', 'pityriasis rosea', 'pseudofolliculitis barbae', 'pseudorhinophyma', 'radiodermatitis', 'scalp psoriasis', 'steroid acne', 'striae', 'tinea cruris', 'ulcer', 'verruca vulgaris', 'xerosis']

# 50% tail class - 82 diseases
SD_128_tails_50_CLASSNAMES = ['acne keloidalis nuchae', 'actinic solar damage(cutis rhomboidalis nuchae)', 'actinic solar damage(solar purpura)', 'actinic solar damage(telangiectasia)', 'androgenetic alopecia', 'angioma', 'angular cheilitis', 'apocrine hydrocystoma', "beau's lines", 'callus', 'candidiasis', 'cellulitis', 'clubbing of fingers', "crowe's sign", 'darier-white disease', 'dermatosis papulosa nigra', 'desquamation', 'digital fibroma', 'dilated pore of winer', 'disseminated actinic porokeratosis', 'drug eruption', 'dry skin eczema', 'epidermal nevus', 'erythema craquele', 'erythema multiforme', 'exfoliative erythroderma', 'fibroma molle', 'fixed drug eruption', 'follicular mucinosis', 'granulation tissue', 'granuloma annulare', 'guttate psoriasis', 'halo nevus', 'herpes simplex virus', 'herpes zoster', 'hidradenitis suppurativa', 'hyperkeratosis palmaris et plantaris', 'hypertrichosis', 'infantile atopic dermatitis', 'junction nevus', 'keloid', 'keratolysis exfoliativa of wende', 'keratosis pilaris', 'kerion', 'koilonychia', 'lentigo maligna melanoma', 'leukocytoclastic vasculitis', 'leukonychia', 'lichen planus', 'lichen sclerosis et atrophicus', 'lichen simplex chronicus', 'lipoma', 'livedo reticularis', 'lymphocytic infiltrate of jessner', 'median nail dystrophy', 'metastatic carcinoma', 'milia', 'myxoid cyst', 'nail dystrophy', 'nail psoriasis', 'neurodermatitis', 'neurofibroma', 'nevus sebaceous of jadassohn', 'nevus spilus', 'nummular eczema', 'onycholysis', 'onychoschizia', 'paronychia', 'pitted keratolysis', 'pityriasis rosea', 'pseudofolliculitis barbae', 'pseudorhinophyma', 'pustular psoriasis', 'radiodermatitis', 'scalp psoriasis', 'steroid acne', 'striae', 'syringoma', 'tinea cruris', 'ulcer', 'verruca vulgaris', 'xerosis']

# SD-tails(SD198 - SD128) - 70 tail diseases
SD_tails_CLASSNAMES = ['eccrine poroma', 'mucous membrane psoriasis', 'cafe au lait macule', 'erythema annulare centrifigum', 'linear epidermal nevus', 'subungual hematoma', 'discoid lupus erythematosus', 'trichofolliculoma', 'mal perforans', 'varicella', 'lymphangioma circumscriptum', 'poikiloderma atrophicans vasculare', 'balanitis xerotica obliterans', "behcet's syndrome", 'ganglion', 'green nail', "kyrle's disease", 'racquet nail', "becker's nevus", 'pearl penile papules', 'frictional lichenoid dermatitis', 'bowenoid papulosis', "schamberg's disease", 'lichen spinulosis', 'wound infection', 'follicular retention cyst', 'fibroma', 'half and half nail', 'acrokeratosis verruciformis', 'erythema ab igne', 'actinic solar damage(actinic cheilitis)', 'epithelioma adenoides cysticum', 'lymphomatoid papulosis', 'nail ridging', 'onychogryphosis', 'hailey hailey disease', 'stomatitis', "terry's nails", 'morphea', 'steroid striae', 'pincer nail syndrome', 'toe deformity', 'pyoderma gangrenosum', 'geographic tongue', 'nevus comedonicus', 'urticaria', 'cutis marmorata', 'mucha habermann disease', 'impetigo', 'aphthous ulcer', 'trichilemmal cyst', 'arsenical keratosis', 'molluscum contagiosum', 'cutaneous t-cell lymphoma', 'trichostasis spinulosa', 'cutanea larva migrans', 'chalazion', 'neurotic excoriations', 'fordyce spots', 'scarring alopecia', 'acute eczema', 'strawberry hemangioma', 'histiocytosis x', 'pityriasis alba', 'melasma', 'leiomyoma', 'vitiligo', 'nail nevus', 'pomade acne', 'solar lentigo']

# SNU-tails(less than 15 samples) - 85 tail diseases
SNU_tails_CLASSNAMES = ['paronychia', 'ota nevus', 'condyloma', 'keloid', 'alopecia areata', 'cellulitis', 'wart', 'riehl melanosis', 'furuncle', 'bullous disease', 'herpes simplex', 'tinea faciale', 'pompholyx', 'nevus spilus', 'androgenic alopecia', 'prurigo nodularis', 'lymphangioma', 'hypertrophic scar', 'idiopathic guttate hypomelanosis', 'keratoderma', 'erythema ab igne', 'lichen striatus', 'ingrowing nail', 'varicella', 'cafe au lait macule', 'eczema herpeticum', 'milia', 'nail dystrophy', 'lichen nitidus', 'acanthosis nigricans', 'angular cheilitis', 'confluent and reticulated papillomatosis', 'syringoma', 'mucous cyst', 'becker nevus', 'psoriasis', 'neurofibromatosis', 'xanthelasma', 'molluscum contagiosum', 'erythema annulare centrifugum', 'onychomycosis', 'neurofibroma', 'mucosal melanotic macule', 'angiofibroma', 'melanonychia', 'organoid nevus', 'nevus depigmentosus', 'epidermal nevus', 'freckle', 'vitiligo', 'poroma', 'viral exanthem', 'blue nevus', 'acne', 'venous lake', 'atopic dermatitis', 'seborrheic dermatitis', 'lichen planus', 'abscess', 'acute generalized exanthematous pustulosis', 'prurigo pigmentosa', 'pityriasis lichenoides chronica', 'granuloma annulare', 'amyloidosis', 'livedo reticularis', 'steatocystoma multiplex', 'mucocele', 'erythema multiforme', 'palmoplantar pustulosis', 'porokeratosis', 'lentigo', 'erythema nodosum', 'inflammed cyst', 'staphylococcal scalded skin syndrome', 'contact dermatitis', 'verruca plana', 'congenital nevus', 'guttate psoriasis', 'angiokeratoma', 'tinea pedis', 'insect bite', 'pigmented progressive purpuric dermatosis', 'skin tag', 'abnormal', 'pustular psoriasis']

DAFFODIL_5_CLASSNAMES = ['vitiligo', 'acne', 'SJS/TEN', 'hyperpigmentation', 'nail psoriasis']

# MIDAS_CLASSNAMES = ('basal cell carcinoma', 'squamous cell carcinoma', 'squamous cell carcinoma in situ', 'melanoma', 'melanocytic nevus', 'actinic solar damage(actinic keratosis)', 'seborrheic keratosis', 'hemangioma', 'dermatofibroma', 'excision (severe, spitz, aimp)', 'fibrous papule')
MIDAS_CLASSNAMES = ('basal cell carcinoma', 'squamous cell carcinoma', 'squamous cell carcinoma in situ', 'melanoma', 'melanocytic nevus', 'actinic solar damage(actinic keratosis)', 'seborrheic keratosis', 'hemangioma', 'dermatofibroma', 'fibrous papule')

MIDAS_BINARY_CLASSNAMES = ('benign', 'malignant')

# Class names expanded with their Derm1M ontology path (hierarchical metrics)
SD_128_CLASSNAMES_WITH_ONTOLOGY_EXTENDED = ['acne keloidalis nuchae', 'acne vulgaris', 'actinic solar damage(actinic keratosis)', 'actinic solar damage(cutis rhomboidalis nuchae)', 'actinic solar damage(pigmentation)', 'actinic solar damage(solar elastosis)', 'actinic solar damage(solar purpura)', 'actinic solar damage(telangiectasia)', 'allergic contact dermatitis', 'alopecia areata', 'androgenetic alopecia', 'angioma', 'angular cheilitis', 'apocrine hydrocystoma', 'basal cell carcinoma', "beau's lines", 'benign keratosis', 'blue nevus', "bowen's disease", 'callus', 'candidiasis', 'cellulitis', 'clubbing of fingers', 'compound nevus', 'congenital nevus', "crowe's sign", 'cutaneous horn', 'darier-white disease', 'dermatofibroma', 'dermatosis papulosa nigra', 'desquamation', 'digital fibroma', 'dilated pore of winer', 'disseminated actinic porokeratosis', 'drug eruption', 'dry skin eczema', 'dyshidrosiform eczema', 'dysplastic nevus', 'eczema', 'epidermal nevus', 'epidermoid cyst', 'erythema craquele', 'erythema multiforme', 'exfoliative erythroderma', 'factitial dermatitis', 'favre racouchot', 'fibroma molle', 'fixed drug eruption', 'follicular mucinosis', 'granulation tissue', 'granuloma annulare', 'guttate psoriasis', 'halo nevus', 'herpes simplex virus', 'herpes zoster', 'hidradenitis suppurativa', 'hyperkeratosis palmaris et plantaris', 'hypertrichosis', 'ichthyosis', 'infantile atopic dermatitis', 'inverse psoriasis', 'junction nevus', 'keloid', 'keratoacanthoma', 'keratolysis exfoliativa of wende', 'keratosis pilaris', 'kerion', 'koilonychia', 'lentigo maligna melanoma', 'leukocytoclastic vasculitis', 'leukonychia', 'lichen planus', 'lichen sclerosis et atrophicus', 'lichen simplex chronicus', 'lipoma', 'livedo reticularis', 'lymphocytic infiltrate of jessner', 'malignant melanoma', 'median nail dystrophy', 'metastatic carcinoma', 'milia', 'myxoid cyst', 'nail dystrophy', 'nail psoriasis', 'neurodermatitis', 'neurofibroma', 'nevus incipiens', 'nevus sebaceous of jadassohn', 'nevus spilus', 'nummular eczema', 'onycholysis', 'onychomycosis', 'onychoschizia', 'paronychia', 'perioral dermatitis', 'pitted keratolysis', 'pityriasis rosea', 'pityrosporum folliculitis', 'pseudofolliculitis barbae', 'pseudorhinophyma', 'psoriasis', 'pustular psoriasis', 'pyogenic granuloma', 'radiodermatitis', 'rhinophyma', 'rosacea', 'scalp psoriasis', 'scar', 'sebaceous gland hyperplasia', 'seborrheic dermatitis', 'seborrheic keratosis', 'skin tag', 'stasis dermatitis', 'stasis edema', 'stasis ulcer', 'steroid acne', 'steroid use abusemisuse dermatitis', 'striae', 'syringoma', 'tinea corporis', 'tinea cruris', 'tinea faciale', 'tinea manus', 'tinea pedis', 'tinea versicolor', 'ulcer', 'verruca vulgaris', 'xerosis', 'bacterial', 'benign', 'benign melanocytic', 'benign non-melanocytic', 'cysts, cyst', 'exogenous', 'fungal', 'hair diseases', 'hereditary', 'infectious', 'inflammatory', 'malignant', 'malignant melanocytic', 'malignant non-melanocytic', 'nail diseases, nail disease', 'non-infectious', 'physical', 'proliferations', 'reaction patterns and descriptive terms', 'ulcers, erosion of skin', 'viral']
SNU_134_CLASSNAMES_WITH_ONTOLOGY_EXTENDED = ['epidermal cyst', 'paronychia', 'ota nevus', 'condyloma', 'keloid', 'alopecia areata', 'cellulitis', 'pyogenic granuloma', 'fifth disease', 'dermatofibroma', 'perioral dermatitis', 'squamous cell carcinoma', 'wart', 'riehl melanosis', 'urticaria pigmentosa', 'furuncle', 'bullous disease', 'herpes simplex', 'tinea faciale', 'lupus erythematosus', 'striae distensae', 'hemangioma', 'herpes zoster', 'malignant melanoma', 'pityriasis lichenoides et varioliformis acuta', 'pompholyx', 'nevus spilus', 'juvenile xanthogranuloma', 'actinic keratosis', 'nummular eczema', 'folliculitis', 'xerotic eczema', 'subungual hematoma', 'androgenic alopecia', 'prurigo nodularis', 'hand eczema', 'basal cell carcinoma', 'melanocytic nevus', 'lymphangioma', 'seborrheic keratosis', 'hypertrophic scar', 'idiopathic guttate hypomelanosis', 'keratoderma', 'erythema ab igne', 'lichen striatus', 'ingrowing nail', 'varicella', 'cafe au lait macule', 'poikiloderma', 'morphea', 'eczema herpeticum', 'milia', 'nail dystrophy', 'lichen nitidus', 'acanthosis nigricans', 'angular cheilitis', 'confluent and reticulated papillomatosis', 'syringoma', 'mucous cyst', 'becker nevus', 'tinea versicolor', 'psoriasis', 'port wine stain', 'neurofibromatosis', 'tinea cruris', 'xanthelasma', 'molluscum contagiosum', 'erythema annulare centrifugum', 'onychomycosis', 'scabies', 'neurofibroma', 'mucosal melanotic macule', 'rosacea', 'keratoacanthoma', 'angiofibroma', 'melanonychia', 'organoid nevus', 'nevus depigmentosus', 'epidermal nevus', 'tinea corporis', 'drug eruption', 'freckle', 'vitiligo', 'poroma', 'pityriasis alba', 'viral exanthem', 'blue nevus', 'acne', 'venous lake', 'atopic dermatitis', 'seborrheic dermatitis', 'lichen planus', 'exfoliative dermatitis', 'melasma', 'abscess', 'acute generalized exanthematous pustulosis', 'urticarial vasculitis', 'vasculitis', 'prurigo pigmentosa', 'impetigo', 'pityriasis lichenoides chronica', 'bowen disease', 'granuloma annulare', 'amyloidosis', 'urticaria', 'keratosis pilaris', 'livedo reticularis', 'steatocystoma multiplex', 'pityriasis rosea', 'mucocele', 'erythema multiforme', 'sebaceous hyperplasia', 'palmoplantar pustulosis', 'porokeratosis', 'lentigo', 'erythema nodosum', 'inflammed cyst', 'staphylococcal scalded skin syndrome', 'contact dermatitis', 'verruca plana', 'congenital nevus', 'lichen simplex chronicus', 'guttate psoriasis', 'angiokeratoma', 'tinea pedis', 'insect bite', 'pigmented progressive purpuric dermatosis', 'pyoderma gangrenosum', 'skin tag', 'lichen amyloidosis', 'abnormal', 'onycholysis', 'pustular psoriasis', 'telangiectasia', 'bacterial', 'benign', 'benign melanocytic', 'benign non-melanocytic', 'cutaneous lupus', 'cysts, cyst', 'dermatitis (acute and chronic)', 'exogenous', 'fungal', 'hair diseases', 'hereditary', 'hyperpigmentation', 'hypersensitivity, allergic reaction', 'infectious', 'inflammatory', 'malignant', 'malignant melanocytic', 'malignant non-melanocytic', 'nail diseases, nail disease', 'non-infectious', 'parasitic', 'pityriasis lichenoides', 'proliferations', 'prurigo', 'pyoderma', 'reaction patterns and descriptive terms', 'scar', 'sunburn', 'verruca vulgaris', 'viral', 'xerosis']
F17K_113_CLASSNAMES_WITH_ONTOLOGY_EXTENDED = ['dermatofibroma', 'psoriasis', 'kaposi sarcoma', 'neutrophilic dermatoses', 'granuloma annulare', 'naevus comedonicus', 'milia', 'telangiectases', 'lichen planus', 'perioral dermatitis', 'paronychia', 'hidradenitis', 'neurodermatitis', 'necrobiosis lipoidica', 'superficial spreading melanoma ssm', 'actinic keratosis', 'basal cell carcinoma', 'acne', 'acne vulgaris', 'allergic contact dermatitis', 'acquired autoimmune bullous diseaseherpes gestationis', 'rhinophyma', 'porokeratosis actinic', 'lupus subacute', 'livedo reticularis', 'folliculitis', 'disseminated actinic porokeratosis', 'pityriasis rubra pilaris', 'porphyria', 'rosacea', 'melanoma', 'sarcoidosis', 'squamous cell carcinoma', 'prurigo nodularis', 'tuberous sclerosis', 'lentigo maligna', 'erythema annulare centrifigum', 'urticaria', 'pustular psoriasis', 'congenital nevus', 'dariers disease', 'dyshidrotic eczema', 'eczema', 'mycosis fungoides', 'sun damaged skin', 'urticaria pigmentosa', 'malignant melanoma', 'fixed eruptions', 'pyogenic granuloma', 'stevens johnson syndrome', 'scabies', 'neurofibromatosis', 'erythema multiforme', 'aplasia cutis', 'behcets disease', 'nevocytic nevus', 'langerhans cell histiocytosis', 'vitiligo', 'dermatomyositis', 'pityriasis rosea', 'fordyce spots', 'scleromyxedema', 'pityriasis lichenoides chronica', 'tick bite', 'scleroderma', 'nevus sebaceous of jadassohn', 'seborrheic keratosis', 'stasis edema', 'lyme disease', 'porokeratosis of mibelli', 'xanthomas', 'pediculosis lids', 'becker nevus', 'striae', 'juvenile xanthogranuloma', 'lupus erythematosus', 'acrodermatitis enteropathica', 'nematode infection', 'basal cell carcinoma morpheiform', 'photodermatoses', 'incontinentia pigmenti', 'drug induced pigmentary changes', 'granuloma pyogenic', 'port wine stain', 'keratosis pilaris', 'mucinosis', 'papilomatosis confluentes and reticulate', 'syringoma', 'acanthosis nigricans', 'drug eruption', 'xeroderma pigmentosum', 'halo nevus', 'lichen amyloidosis', 'ehlers danlos syndrome', 'solid cystic basal cell carcinoma', 'epidermal nevus', 'ichthyosis vulgaris', 'keloid', 'mucous cyst', 'calcinosis cutis', 'lymphangioma', 'seborrheic dermatitis', 'pilomatricoma', 'pilar cyst', 'erythema nodosum', 'neurotic excoriations', 'hailey hailey disease', 'erythema elevatum diutinum', 'factitial dermatitis', 'tungiasis', 'epidermolysis bullosa', 'myiasis', 'cheilitis', 'lichen simplex', 'bacterial', 'benign', 'benign melanocytic', 'benign non-melanocytic', 'bullous disease', 'cysts, cyst', 'exogenous', 'hereditary', 'hyperpigmentation', 'hypersensitivity, allergic reaction', 'infectious', 'inflammatory', 'irritant contact dermatitis', 'malignant', 'malignant melanocytic', 'malignant non-melanocytic', 'nail diseases, nail disease', 'non-infectious', 'parasitic', 'physical', 'pityriasis lichenoides', 'porokeratosis', 'proliferations', 'prurigo', 'reaction patterns and descriptive terms']